services:

  # --- Serviço do Banco de Dados PostgreSQL ---
  db:
    image: postgres:16
    container_name: keycloak-db
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Serviço do Keycloak ---
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak-broker
    restart: always
    command: start-dev
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: server.adekz.com
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
    ports:
      - "18400:8080"
    networks:
      - keycloak-net
    depends_on:
      db:
        condition: service_healthy

# --- Seção para definir a rede customizada --- #
networks:
  keycloak-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.100.8/29
          gateway: 172.1.100.9
